<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>justfile</string>
    <string>Justfile</string>
    <string>.justfile</string>
  </array>

  <key>name</key>
  <string>Just</string>

  <key>scopeName</key>
  <string>source.just</string>

  <key>uuid</key>
  <string>B2C3D4E5-JUST-4F6E-8A9B-1C2D3E4F5A6B</string>

  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>

    <dict>
      <key>include</key>
      <string>#attributes</string>
    </dict>

    <dict>
      <key>include</key>
      <string>#directives</string>
    </dict>

    <dict>
      <key>include</key>
      <string>#recipe</string>
    </dict>

    <dict>
      <key>include</key>
      <string>#assignments</string>
    </dict>

    <dict>
      <key>include</key>
      <string>#expressions</string>
    </dict>
  </array>

  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>comment.line.number-sign.just</string>
          <key>match</key>
          <string>#.*$</string>
        </dict>
      </array>
    </dict>

    <key>attributes</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^\s*(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.brackets.begin.just</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(\])\s*$</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.brackets.end.just</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.annotation.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>entity.name.annotation.just</string>
              <key>match</key>
              <string>\b(group|private|deprecated|no-cd|linux|macos|windows|unix)\b</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#expressions</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>

    <key>directives</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.directive.import.just</string>
          <key>match</key>
          <string>^\s*(import|mod)\b\s*(.*)$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.import.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#strings</string>
                </dict>
                <dict>
                  <key>name</key>
                  <string>entity.name.module.just</string>
                  <key>match</key>
                  <string>[A-Za-z_][A-Za-z0-9_\-]*(?:::[A-Za-z_][A-Za-z0-9_\-]*)*</string>
                </dict>
              </array>
            </dict>
          </dict>
        </dict>

        <dict>
          <key>name</key>
          <string>meta.directive.set.just</string>
          <key>match</key>
          <string>^\s*(set)\s+([A-Za-z][A-Za-z\-]*)\s*(:=)\s*(.*)$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.set.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.constant.setting.just</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.assignment.just</string>
            </dict>
            <key>4</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#expressions</string>
                </dict>
              </array>
            </dict>
          </dict>
        </dict>

        <dict>
          <key>name</key>
          <string>meta.directive.alias.just</string>
          <key>match</key>
          <string>^\s*(alias)\s+([A-Za-z_][A-Za-z0-9_\-]*)\s*(:=)\s*([A-Za-z_][A-Za-z0-9_\-]*(?:::[A-Za-z_][A-Za-z0-9_\-]*)*)\s*$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.alias.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.alias.just</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.assignment.just</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.target.just</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>

    <key>assignments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.assignment.export.just</string>
          <key>match</key>
          <string>^\s*(export|unexport)\s+([A-Za-z_][A-Za-z0-9_\-]*)\s*(:=)\s*(.*)$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.export.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.just</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.assignment.just</string>
            </dict>
            <key>4</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#expressions</string>
                </dict>
              </array>
            </dict>
          </dict>
        </dict>

        <dict>
          <key>name</key>
          <string>meta.assignment.variable.just</string>
          <key>match</key>
          <string>^\s*([A-Za-z_][A-Za-z0-9_\-]*)\s*(:=)\s*(.*)$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.assignment.just</string>
            </dict>
            <key>3</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#expressions</string>
                </dict>
              </array>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>

    <key>recipe</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.recipe.definition.just</string>
          <key>match</key>
          <string>^\s*(@?[A-Za-z_][A-Za-z0-9_\-]*)\s*((?:\s+(?:\$?[A-Za-z_][A-Za-z0-9_\-]*(?:\s*=\s*[^\s:]+)?|[+*][A-Za-z_][A-Za-z0-9_\-]*))*)\s*(:)\s*(.*?)\s*$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.recipe.just</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.just</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.key-value.just</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>meta.recipe.dependencies.just</string>
            </dict>
          </dict>
        </dict>

        <dict>
          <key>begin</key>
          <string>^(?=[ \t]+\S)</string>
          <key>end</key>
          <string>(?=^(?![ \t])\S)|\z</string>
          <key>name</key>
          <string>meta.recipe.body.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>punctuation.whitespace.indent.just</string>
              <key>match</key>
              <string>^[ \t]+</string>
            </dict>

            <dict>
              <key>name</key>
              <string>comment.line.shebang.just</string>
              <key>match</key>
              <string>^[ \t]*#!.*$</string>
            </dict>

            <dict>
              <key>name</key>
              <string>keyword.operator.prefix.just</string>
              <key>match</key>
              <string>^[ \t]*[@\-]</string>
            </dict>

            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>

            <dict>
              <key>include</key>
              <string>source.shell</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>

    <key>expressions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>

        <dict>
          <key>include</key>
          <string>#backticks</string>
        </dict>

        <dict>
          <key>include</key>
          <string>#interpolation</string>
        </dict>

        <dict>
          <key>name</key>
          <string>keyword.control.conditional.just</string>
          <key>match</key>
          <string>\b(if|else)\b</string>
        </dict>

        <dict>
          <key>name</key>
          <string>constant.language.boolean.just</string>
          <key>match</key>
          <string>\b(true|false)\b</string>
        </dict>

        <dict>
          <key>name</key>
          <string>keyword.operator.logical.just</string>
          <key>match</key>
          <string>&amp;&amp;|\|\|</string>
        </dict>

        <dict>
          <key>name</key>
          <string>keyword.operator.comparison.just</string>
          <key>match</key>
          <string>==|!=|=~|!~|&lt;=|&gt;=|&lt;|&gt;</string>
        </dict>

        <dict>
          <key>name</key>
          <string>keyword.operator.arithmetic.just</string>
          <key>match</key>
          <string>[+\-/]</string>
        </dict>

        <dict>
          <key>name</key>
          <string>support.function.builtin.just</string>
          <key>match</key>
          <string>\b(env|env_var|env_var_or_default|require|which|arch|os|os_family|num_cpus|invocation_directory|invocation_directory_native|justfile|justfile_directory|source_file|source_directory|just_executable|just_pid|is_dependency|uuid|choose|sha256|sha256_file|blake3|blake3_file|datetime|datetime_utc|shell|semver_matches|error|read|style|absolute_path|canonicalize|clean|join|extension|file_name|file_stem|parent_directory|without_extension|path_exists|append|prepend|encode_uri_component|quote|replace|replace_regex|trim|trim_start|trim_end|trim_start_match|trim_end_match|trim_start_matches|trim_end_matches|capitalize|lowercase|uppercase|snakecase|kebabcase|titlecase|uppercamelcase|lowercamelcase|home_directory|config_directory|data_directory|cache_directory|executable_directory)\s*(?=\()</string>
        </dict>

        <dict>
          <key>name</key>
          <string>constant.language.just</string>
          <key>match</key>
          <string>\b(HEX|HEXLOWER|HEXUPPER|PATH_SEP|PATH_VAR_SEP|CLEAR|NORMAL|BOLD|ITALIC|UNDERLINE|INVERT|HIDE|STRIKETHROUGH|BLACK|RED|GREEN|YELLOW|BLUE|MAGENTA|CYAN|WHITE|BG_BLACK|BG_RED|BG_GREEN|BG_YELLOW|BG_BLUE|BG_MAGENTA|BG_CYAN|BG_WHITE)\b</string>
        </dict>

        <dict>
          <key>name</key>
          <string>variable.other.just</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_\-]*\b</string>
        </dict>
      </array>
    </dict>

    <key>interpolation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\{\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.interpolation.begin.just</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.interpolation.end.just</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.interpolation.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#backticks</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#expressions</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>

    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>[fx]?"""</string>
          <key>end</key>
          <string>"""</string>
          <key>name</key>
          <string>string.quoted.triple.double.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.escape.just</string>
              <key>match</key>
              <string>\\.</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
          </array>
        </dict>

        <dict>
          <key>begin</key>
          <string>[fx]?'''</string>
          <key>end</key>
          <string>'''</string>
          <key>name</key>
          <string>string.quoted.triple.single.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
          </array>
        </dict>

        <dict>
          <key>begin</key>
          <string>[fx]?"</string>
          <key>end</key>
          <string>"</string>
          <key>name</key>
          <string>string.quoted.double.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.escape.just</string>
              <key>match</key>
              <string>\\.</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
          </array>
        </dict>

        <dict>
          <key>begin</key>
          <string>[fx]?'</string>
          <key>end</key>
          <string>'</string>
          <key>name</key>
          <string>string.quoted.single.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>

    <key>backticks</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>```</string>
          <key>end</key>
          <string>```</string>
          <key>name</key>
          <string>string.interpolated.backtick.triple.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
            <dict>
              <key>include</key>
              <string>source.shell</string>
            </dict>
          </array>
        </dict>

        <dict>
          <key>begin</key>
          <string>`</string>
          <key>end</key>
          <string>`</string>
          <key>name</key>
          <string>string.interpolated.backtick.just</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#interpolation</string>
            </dict>
            <dict>
              <key>include</key>
              <string>source.shell</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
  </dict>
</dict>
</plist>
